#!/bin/python3

import logging
import argparse

from ctfi2.gui.gui import run

if __name__ == '__main__':
    log_level = logging.DEBUG
    logging.basicConfig(level=log_level)

    parser = argparse.ArgumentParser(description='ctfi2 - Remotely manage your CTFd server instance')

    parser.add_argument('-G', action='store_true', help='Start the GUI')
    parser.add_argument('-C', action='store_true', help='Start the CLI')

    args = parser.parse_args()

    if args.C:
        # Future Use
        pass

    elif args.G:
        run(log_level)

    else:
        run(log_level)
        # parser.print_help()
